// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/bank/type/accounts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_Currency_UNSPECEFIED Currency = 0
	Currency_USD                  Currency = 1
	Currency_JPY                  Currency = 2
	Currency_CAD                  Currency = 3
	Currency_EUR                  Currency = 4
	Currency_GBP                  Currency = 5
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "Currency_UNSPECEFIED",
		1: "USD",
		2: "JPY",
		3: "CAD",
		4: "EUR",
		5: "GBP",
	}
	Currency_value = map[string]int32{
		"Currency_UNSPECEFIED": 0,
		"USD":                  1,
		"JPY":                  2,
		"CAD":                  3,
		"EUR":                  4,
		"GBP":                  5,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bank_type_accounts_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_proto_bank_type_accounts_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_proto_bank_type_accounts_proto_rawDescGZIP(), []int{0}
}

type BankAccountCreateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber  string                 `protobuf:"bytes,1,opt,name=AccountNumber,json=account_number,proto3" json:"AccountNumber,omitempty"`
	AccountName    string                 `protobuf:"bytes,2,opt,name=AccountName,json=account_name,proto3" json:"AccountName,omitempty"`
	Currency       Currency               `protobuf:"varint,3,opt,name=Currency,json=currency,proto3,enum=bank.Currency" json:"Currency,omitempty"`
	CurrentBalance float64                `protobuf:"fixed64,4,opt,name=CurrentBalance,json=current_balance,proto3" json:"CurrentBalance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BankAccountCreateRequest) Reset() {
	*x = BankAccountCreateRequest{}
	mi := &file_proto_bank_type_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccountCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccountCreateRequest) ProtoMessage() {}

func (x *BankAccountCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccountCreateRequest.ProtoReflect.Descriptor instead.
func (*BankAccountCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *BankAccountCreateRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *BankAccountCreateRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *BankAccountCreateRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_Currency_UNSPECEFIED
}

func (x *BankAccountCreateRequest) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

type BankAccountCreateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountUUID    string                 `protobuf:"bytes,1,opt,name=AccountUUID,json=account_uuid,proto3" json:"AccountUUID,omitempty"`
	AccountNumber  string                 `protobuf:"bytes,2,opt,name=AccountNumber,json=account_number,proto3" json:"AccountNumber,omitempty"`
	AccountName    string                 `protobuf:"bytes,3,opt,name=AccountName,json=account_name,proto3" json:"AccountName,omitempty"`
	Currency       Currency               `protobuf:"varint,4,opt,name=Currency,json=currency,proto3,enum=bank.Currency" json:"Currency,omitempty"`
	CurrentBalance float64                `protobuf:"fixed64,5,opt,name=CurrentBalance,json=current_balance,proto3" json:"CurrentBalance,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,json=created_at,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,json=updated_at,proto3" json:"UpdatedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BankAccountCreateResponse) Reset() {
	*x = BankAccountCreateResponse{}
	mi := &file_proto_bank_type_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccountCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccountCreateResponse) ProtoMessage() {}

func (x *BankAccountCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccountCreateResponse.ProtoReflect.Descriptor instead.
func (*BankAccountCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *BankAccountCreateResponse) GetAccountUUID() string {
	if x != nil {
		return x.AccountUUID
	}
	return ""
}

func (x *BankAccountCreateResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *BankAccountCreateResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *BankAccountCreateResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_Currency_UNSPECEFIED
}

func (x *BankAccountCreateResponse) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *BankAccountCreateResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BankAccountCreateResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CurrentBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUUID   string                 `protobuf:"bytes,1,opt,name=AccountUUID,json=account_uuid,proto3" json:"AccountUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentBalanceRequest) Reset() {
	*x = CurrentBalanceRequest{}
	mi := &file_proto_bank_type_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalanceRequest) ProtoMessage() {}

func (x *CurrentBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalanceRequest.ProtoReflect.Descriptor instead.
func (*CurrentBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *CurrentBalanceRequest) GetAccountUUID() string {
	if x != nil {
		return x.AccountUUID
	}
	return ""
}

type CurrentBalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountUUID    string                 `protobuf:"bytes,1,opt,name=AccountUUID,json=account_uuid,proto3" json:"AccountUUID,omitempty"`
	Currency       Currency               `protobuf:"varint,2,opt,name=Currency,json=currency,proto3,enum=bank.Currency" json:"Currency,omitempty"`
	CurrentBalance float64                `protobuf:"fixed64,3,opt,name=CurrentBalance,json=current_balance,proto3" json:"CurrentBalance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CurrentBalanceResponse) Reset() {
	*x = CurrentBalanceResponse{}
	mi := &file_proto_bank_type_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalanceResponse) ProtoMessage() {}

func (x *CurrentBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalanceResponse.ProtoReflect.Descriptor instead.
func (*CurrentBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *CurrentBalanceResponse) GetAccountUUID() string {
	if x != nil {
		return x.AccountUUID
	}
	return ""
}

func (x *CurrentBalanceResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_Currency_UNSPECEFIED
}

func (x *CurrentBalanceResponse) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

var File_proto_bank_type_accounts_proto protoreflect.FileDescriptor

var file_proto_bank_type_accounts_proto_rawDesc = string([]byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x62, 0x61, 0x6e, 0x6b, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x01, 0x0a, 0x18, 0x42, 0x61, 0x6e, 0x6b,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0b, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a,
	0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x27, 0x0a, 0x0e, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x22, 0xd3, 0x02, 0x0a, 0x19, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0b, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a,
	0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x27, 0x0a, 0x0e, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x12, 0x39,
	0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x22, 0x3a, 0x0a, 0x15, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x55, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x16, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x55, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x27, 0x0a, 0x0e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2a, 0x51, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x45, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x55, 0x53, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4a, 0x50, 0x59, 0x10, 0x02,
	0x12, 0x07, 0x0a, 0x03, 0x43, 0x41, 0x44, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x55, 0x52,
	0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x42, 0x50, 0x10, 0x05, 0x42, 0x0d, 0x5a, 0x0b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_proto_bank_type_accounts_proto_rawDescOnce sync.Once
	file_proto_bank_type_accounts_proto_rawDescData []byte
)

func file_proto_bank_type_accounts_proto_rawDescGZIP() []byte {
	file_proto_bank_type_accounts_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_accounts_proto_rawDesc), len(file_proto_bank_type_accounts_proto_rawDesc)))
	})
	return file_proto_bank_type_accounts_proto_rawDescData
}

var file_proto_bank_type_accounts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_bank_type_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_bank_type_accounts_proto_goTypes = []any{
	(Currency)(0),                     // 0: bank.Currency
	(*BankAccountCreateRequest)(nil),  // 1: bank.BankAccountCreateRequest
	(*BankAccountCreateResponse)(nil), // 2: bank.BankAccountCreateResponse
	(*CurrentBalanceRequest)(nil),     // 3: bank.CurrentBalanceRequest
	(*CurrentBalanceResponse)(nil),    // 4: bank.CurrentBalanceResponse
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_proto_bank_type_accounts_proto_depIdxs = []int32{
	0, // 0: bank.BankAccountCreateRequest.Currency:type_name -> bank.Currency
	0, // 1: bank.BankAccountCreateResponse.Currency:type_name -> bank.Currency
	5, // 2: bank.BankAccountCreateResponse.CreatedAt:type_name -> google.protobuf.Timestamp
	5, // 3: bank.BankAccountCreateResponse.UpdatedAt:type_name -> google.protobuf.Timestamp
	0, // 4: bank.CurrentBalanceResponse.Currency:type_name -> bank.Currency
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_bank_type_accounts_proto_init() }
func file_proto_bank_type_accounts_proto_init() {
	if File_proto_bank_type_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_accounts_proto_rawDesc), len(file_proto_bank_type_accounts_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_accounts_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_accounts_proto_depIdxs,
		EnumInfos:         file_proto_bank_type_accounts_proto_enumTypes,
		MessageInfos:      file_proto_bank_type_accounts_proto_msgTypes,
	}.Build()
	File_proto_bank_type_accounts_proto = out.File
	file_proto_bank_type_accounts_proto_goTypes = nil
	file_proto_bank_type_accounts_proto_depIdxs = nil
}
