// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/bank/type/transfer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferStatus int32

const (
	TransferStatus_TransferStatus_UNSPECIFIED TransferStatus = 0
	TransferStatus_Failed                     TransferStatus = 1
	TransferStatus_Succes                     TransferStatus = 2
)

// Enum value maps for TransferStatus.
var (
	TransferStatus_name = map[int32]string{
		0: "TransferStatus_UNSPECIFIED",
		1: "Failed",
		2: "Succes",
	}
	TransferStatus_value = map[string]int32{
		"TransferStatus_UNSPECIFIED": 0,
		"Failed":                     1,
		"Succes":                     2,
	}
)

func (x TransferStatus) Enum() *TransferStatus {
	p := new(TransferStatus)
	*p = x
	return p
}

func (x TransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bank_type_transfer_proto_enumTypes[0].Descriptor()
}

func (TransferStatus) Type() protoreflect.EnumType {
	return &file_proto_bank_type_transfer_proto_enumTypes[0]
}

func (x TransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatus.Descriptor instead.
func (TransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_bank_type_transfer_proto_rawDescGZIP(), []int{0}
}

type BankTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccount   string                 `protobuf:"bytes,1,opt,name=FromAccount,json=from_account,proto3" json:"FromAccount,omitempty"`
	ToAccount     string                 `protobuf:"bytes,2,opt,name=ToAccount,json=to_account,proto3" json:"ToAccount,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Currency      Currency               `protobuf:"varint,4,opt,name=Currency,json=currency,proto3,enum=bank.Currency" json:"Currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankTransferRequest) Reset() {
	*x = BankTransferRequest{}
	mi := &file_proto_bank_type_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankTransferRequest) ProtoMessage() {}

func (x *BankTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankTransferRequest.ProtoReflect.Descriptor instead.
func (*BankTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *BankTransferRequest) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *BankTransferRequest) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *BankTransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BankTransferRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_Currency_UNSPECEFIED
}

type BankTransferResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromAccount    string                 `protobuf:"bytes,1,opt,name=FromAccount,json=from_account,proto3" json:"FromAccount,omitempty"`
	ToAccount      string                 `protobuf:"bytes,2,opt,name=ToAccount,json=to_account,proto3" json:"ToAccount,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Currency       Currency               `protobuf:"varint,4,opt,name=Currency,json=currency,proto3,enum=bank.Currency" json:"Currency,omitempty"`
	TransferStatus TransferStatus         `protobuf:"varint,5,opt,name=TransferStatus,json=transfer_status,proto3,enum=bank.TransferStatus" json:"TransferStatus,omitempty"`
	Time           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=Time,json=time,proto3" json:"Time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BankTransferResponse) Reset() {
	*x = BankTransferResponse{}
	mi := &file_proto_bank_type_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankTransferResponse) ProtoMessage() {}

func (x *BankTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankTransferResponse.ProtoReflect.Descriptor instead.
func (*BankTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *BankTransferResponse) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *BankTransferResponse) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *BankTransferResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BankTransferResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_Currency_UNSPECEFIED
}

func (x *BankTransferResponse) GetTransferStatus() TransferStatus {
	if x != nil {
		return x.TransferStatus
	}
	return TransferStatus_TransferStatus_UNSPECIFIED
}

func (x *BankTransferResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_proto_bank_type_transfer_proto protoreflect.FileDescriptor

var file_proto_bank_type_transfer_proto_rawDesc = string([]byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x62, 0x61, 0x6e, 0x6b, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61,
	0x6e, 0x6b, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x13, 0x42, 0x61, 0x6e, 0x6b,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0b, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x09, 0x54, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x08, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x62, 0x61,
	0x6e, 0x6b, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x8b, 0x02, 0x0a, 0x14, 0x42, 0x61, 0x6e, 0x6b, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x0b, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1d, 0x0a, 0x09, 0x54, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x6e,
	0x6b, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x3d, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x62,
	0x61, 0x6e, 0x6b, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x2a, 0x48, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x1a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x10, 0x02, 0x42, 0x0d, 0x5a,
	0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_bank_type_transfer_proto_rawDescOnce sync.Once
	file_proto_bank_type_transfer_proto_rawDescData []byte
)

func file_proto_bank_type_transfer_proto_rawDescGZIP() []byte {
	file_proto_bank_type_transfer_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_transfer_proto_rawDesc), len(file_proto_bank_type_transfer_proto_rawDesc)))
	})
	return file_proto_bank_type_transfer_proto_rawDescData
}

var file_proto_bank_type_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_bank_type_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bank_type_transfer_proto_goTypes = []any{
	(TransferStatus)(0),           // 0: bank.TransferStatus
	(*BankTransferRequest)(nil),   // 1: bank.BankTransferRequest
	(*BankTransferResponse)(nil),  // 2: bank.BankTransferResponse
	(Currency)(0),                 // 3: bank.Currency
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_bank_type_transfer_proto_depIdxs = []int32{
	3, // 0: bank.BankTransferRequest.Currency:type_name -> bank.Currency
	3, // 1: bank.BankTransferResponse.Currency:type_name -> bank.Currency
	0, // 2: bank.BankTransferResponse.TransferStatus:type_name -> bank.TransferStatus
	4, // 3: bank.BankTransferResponse.Time:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_bank_type_transfer_proto_init() }
func file_proto_bank_type_transfer_proto_init() {
	if File_proto_bank_type_transfer_proto != nil {
		return
	}
	file_proto_bank_type_accounts_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_transfer_proto_rawDesc), len(file_proto_bank_type_transfer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_transfer_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_transfer_proto_depIdxs,
		EnumInfos:         file_proto_bank_type_transfer_proto_enumTypes,
		MessageInfos:      file_proto_bank_type_transfer_proto_msgTypes,
	}.Build()
	File_proto_bank_type_transfer_proto = out.File
	file_proto_bank_type_transfer_proto_goTypes = nil
	file_proto_bank_type_transfer_proto_depIdxs = nil
}
